### ISSUE TITLE
Use Yarnpkg

### ISSUE THREAD

**Issue by pi0** [Tabrizian/Fandooooooogh#1]
I Suggest to switch from npm to [yarn](https://yarnpkg.com/) ;)

**Comment by Tabrizian** [comment]
I will use yarn, but what is the problem of npm?
@pi0

**Comment by pi0** [comment]
There was enough problems with npm that facebook and google devs decided to develop and open source their alternative solution :)) Just check out docs.

**Comment by Tabrizian** [comment]
Thanks man! :)
